import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for the Veridian IT Desk demo deployment.",
};

/* Plain prose page: no backend, no auth needed. */

const SECTIONS: { heading: string; body: string }[] = [
  {
    heading: "Overview",
    body: "Veridian IT Desk is an assignment submission built for the AIONOS Agentic AI Factory assessment (Assignment 2). This deployment exists so reviewers can try the product. It is a demo, not a production service, and you should not share real personal data with it.",
  },
  {
    heading: "What is collected",
    body: "Account details you sign in with (name, email address, role); the content you create (support threads, messages, tickets, knowledge-base edits); and technical data needed to run the service (server logs, error reports).",
  },
  {
    heading: "How it is used",
    body: "Your content is used only to operate the workspace: running the support agent over your threads, keeping the audit trail, and signing you in. Support messages you write may be shown to IT agents working your requests.",
  },
  {
    heading: "Storage and sharing",
    body: "Data is stored in the deployment's database (MongoDB, or in-memory when unconfigured). Agent replies are generated by an external language-model provider, which receives the text needed to answer. Nothing is sold, and there is no advertising or cross-site tracking.",
  },
  {
    heading: "Cookies",
    body: "A single strictly-necessary session cookie (veridian_access) keeps you signed in. Analytics, if enabled by the site operator, loads only after consent-free internal use and never follows you elsewhere.",
  },
  {
    heading: "Retention",
    body: "This is a demo deployment: data may be wiped at any time (for example via the admin reset) and no retention guarantees are made.",
  },
];

export default function PrivacyPage() {
  return (
    <main className="mx-auto w-full max-w-2xl flex-1 px-4 py-12">
      <h1 className="text-2xl font-bold tracking-tight text-slate-900">Privacy Policy</h1>
      <p className="mt-2 text-sm text-slate-500">
        Veridian IT Desk · demo deployment for assessment purposes.
      </p>
      <div className="mt-8 flex flex-col gap-6">
        {SECTIONS.map((s) => (
          <section key={s.heading}>
            <h2 className="text-base font-semibold text-slate-900">{s.heading}</h2>
            <p className="mt-1 text-sm leading-relaxed text-slate-600">{s.body}</p>
          </section>
        ))}
      </div>
    </main>
  );
}
